variables:
  DOCKER_DRIVER: overlay

stages:
  - package

docker-build:
  only:
    - master
  image: docker:latest
  services:
    - docker:dind
  stage: package
  tags:
    - docker
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
